<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0 (Python 3.11.8 on darwin)" generated="20240318 14:18:59.505" rpa="false" schemaversion="3">
<suite id="s1" name="Work-Book" source="/Users/cococake/Desktop/Odds_Mar/Practing_Robot_1/tests/work-book">
<suite id="s1-s1" name="Test Case" source="/Users/cococake/Desktop/Odds_Mar/Practing_Robot_1/tests/work-book/test_case.robot">
<test id="s1-s1-t1" name="test101" line="14">
<kw name="นับจำนวนคนในชีท Summary" library="workBook-keyword" sourcename="นับจำนวนคนในชีท ${sheet}">
<kw name="Open Workbook">
<arg>testbook2.xlsx</arg>
<msg timestamp="20240318 14:18:59.691" level="FAIL">No keyword with name 'Open Workbook' found.</msg>
<status status="FAIL" starttime="20240318 14:18:59.691" endtime="20240318 14:18:59.691"/>
</kw>
<kw name="Get row count in the sheet" library="workBook-keyword">
<var>${count}</var>
<arg>${sheet}</arg>
<status status="NOT RUN" starttime="20240318 14:18:59.691" endtime="20240318 14:18:59.692"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>หน้า ${sheet} มี ${count-1} แถว</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20240318 14:18:59.692" endtime="20240318 14:18:59.692"/>
</kw>
<status status="FAIL" starttime="20240318 14:18:59.687" endtime="20240318 14:18:59.692"/>
</kw>
<kw name="นับจำนวนคนจาก sheet ทั้งหมด" library="workBook-keyword">
<status status="NOT RUN" starttime="20240318 14:18:59.692" endtime="20240318 14:18:59.692"/>
</kw>
<status status="FAIL" starttime="20240318 14:18:59.686" endtime="20240318 14:18:59.692">No keyword with name 'Open Workbook' found.</status>
</test>
<status status="FAIL" starttime="20240318 14:18:59.530" endtime="20240318 14:18:59.693"/>
</suite>
<status status="FAIL" starttime="20240318 14:18:59.512" endtime="20240318 14:18:59.693"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Work-Book">Work-Book</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Test Case">Work-Book.Test Case</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240318 14:18:59.679" level="ERROR">Error in file '/Users/cococake/Desktop/Odds_Mar/Practing_Robot_1/tests/work-book/workBook-keyword.robot' on line 5: Importing library 'RPA.Excel.Files' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python311.zip
  /usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11
  /usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload
  /usr/local/lib/python3.11/site-packages</msg>
<msg timestamp="20240318 14:18:59.680" level="ERROR">Error in file '/Users/cococake/Desktop/Odds_Mar/Practing_Robot_1/tests/work-book/workBook-keyword.robot' on line 6: Importing library 'RPA.Tables' failed: ModuleNotFoundError: No module named 'RPA'
Traceback (most recent call last):
  None
PYTHONPATH:
  /usr/local/bin
  /usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python311.zip
  /usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11
  /usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload
  /usr/local/lib/python3.11/site-packages</msg>
</errors>
</robot>
